openapi: 3.0.0
x-api-id: mail
info:
  version: 1.0.0
  title: mail
  license:
    name: ISO
servers:
  - url: 'http://localhost:5000'
paths:
  /v1/mails:
    post:
      tags:
        - mails
      description: Returns status of the email (sent/queued/failed)
      parameters: []
      responses:
        '200':
          description: Email will be sent.
        '400':
          description: Email will not be sent.
        '500':
          description: Internal Service Error.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - from
                - subject
                - text
              properties:
                to:
                  type: array
                  minLength: 1
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                cc:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                bcc:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                from:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    name:
                      type: string
                subject:
                  type: string
                text:
                  type: string
  /v1/:
    get:
      tags:
        - health-check
      description: Returns 200 if service is up
      responses:
        '200':
          description: Service is up.