openapi: 3.0.1
info:
  title: email-integration-service
  description: RESTful API for sending emails using multiple email clients
  version: 1.0.0
servers:
- url: /v1
tags:
- name: Mails
  description: Sending Emails endpoint
- name: Specification
  description: The swagger API specification
paths:
  /mails:
    post:
      tags:
        - Mails
      description: Returns status of the email (sent/queued/failed)
      parameters: []
      responses:
        '200':
          description: Email will be sent.
        '400':
          description: Email will not be sent.
        '500':
          description: Internal Service Error.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MailBody'
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    MailBody:
      title: Mail
      required:
        - to
        - from
        - subject
        - text
      type: object
      properties:
        to:
          type: array
          minLength: 1
          description: The name and email address of recpient(s).
          items:
            type: object
            properties:
              email:
                type: string
                format: email
              name:
                type: string
        cc:
          type: array
          description: The name and email address of recpients.
          items:
            type: object
            properties:
              email:
                type: string
                format: email
              name:
                type: string
        bcc:
          type: array
          description: The name and email address of recpients.
          items:
            type: object
            properties:
              email:
                type: string
                format: email
              name:
                type: string
        from:
          type: object
          description: The name and email address of sender.
          properties:
            email:
              type: string
              format: email
            name:
              type: string
        subject:
          description: The subject of the email.
          type: string
        text:
          description: The body of the email in text string only.
          type: string
        service_names:
          description: This is optional param, but if supplied, this will only use the services indicated.
          type: array
          items:
            type: string
            enum: [SendGrid, MailGun]